# Generated by Django 3.1.4 on 2021-01-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('middle_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name="Title, e.g. 'Grammatica Latina'")),
                ('place_of_publication', models.CharField(max_length=256, verbose_name='Place of publication, e.g. Moscow')),
                ('publisher', models.CharField(max_length=256, verbose_name="Publisher, e.g. 'MSU Press'")),
                ('type_of_book', models.CharField(max_length=256, verbose_name="Type of book, e.g. 'Textbook'")),
                ('year', models.DateField(verbose_name='Year of publication')),
                ('isbn', models.PositiveBigIntegerField(verbose_name='ISBN')),
                ('content', models.FileField(upload_to='media/')),
                ('authors', models.ManyToManyField(related_name='books', to='book.Author')),
            ],
        ),
    ]
